### ISSUE TITLE
Missing credentials for scraper. CompanyId: hapoalim

### ISSUE THREAD

**Issue by mynameisguy** [brafdlog/hiuvi#257]
running version 0.2 on mac

when trying to scrape hapoalim I get this error:
```Missing credentials for scraper. CompanyId: hapoalim```

Importing from MAX works.

**Comment by mynameisguy** [comment]
this might be since hapoalim credentials include **userCode** as username, and the code checks only for username, id and num:
https://github.com/brafdlog/hiuvi/blob/e47a54ac4a125342398f1b62c195efa6c7c29835/src/backend/import/bankScraper.ts#L27

**Comment by baruchiro** [comment]
Thanks!
Added to [Milestone 2](https://github.com/brafdlog/hiuvi/milestone/3), if you are going to fix it yourself, please write here.

**Comment by jossef** [comment]
> running version 0.2 on mac
> 
> when trying to scrape hapoalim I get this error:
> `Missing credentials for scraper. CompanyId: hapoalim`
> 
> Importing from MAX works.


Same on windows  
![image](https://user-images.githubusercontent.com/1287098/122798786-a6956480-d2c9-11eb-9208-640ce95b2f4a.png)

**Comment by baruchiro** [comment]
Yes yes, I'm working on it. soon it will be fixed, I just waiting for the review.

You're welcome to review and write your opinion BTW here: #268
